export const STORAGE_KEYS = {
  APP_THEME: "APP_THEME",
  WINDOW_STATE: "WINDOW_STATE",
  LAST_COMPANY: "LAST_COMPANY",
  LAST_BRANCH: "LAST_BRANCH",
  LAST_FINANCIAL_YEAR: "LAST_FINANCIAL_YEAR",
  BACKUP_LOCATION: "BACKUP_LOCATION",
} as const;

export type StorageKey = (typeof STORAGE_KEYS)[keyof typeof STORAGE_KEYS];
